name: CloneZilla with virtualbox+
on:
  push:

    tags:
      - 'v*' 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update repo
        run: sudo apt update 
        
      - name: build
        run: |
          sudo apt install util-linux squashfs-tools curl mkisofs xorriso xz-utils
          sudo ./build.sh clonezilla.iso clonezilla_with_virtualbox.iso
     
      - name: Upload Release Assets
        run: |
            set -x
            assets=()
            for asset in "./clonezilla_with_virtualbox.iso" "./checksums.txt"; do
            assets+=("-a" "$asset")
            done
            tag_name="${GITHUB_REF##*/}"
            hub release create  "${assets[@]}" \
            -m "Release $tag_name" \
            -m "This release was automatically created by the Git Actions workflow corresponding to directory .github in the repository." \
            -m "The input of this release is the CloneZilla release linked to in the Readme." "$tag_name"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
      
      
